version: 2
updates:
  # Maintain dependencies for GitHub Actions - Update once every week.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "type: dependencies"
      - "status: needs review"
      - "team: n/a"
      - "prio: low"

  # Maintain dependencies for Convoy Bridge (Rust) - Update once every week.
  - package-ecosystem: "cargo"
    directory: "/applications/convoy_bridge"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "type: dependencies"
      - "status: needs review"
      - "team: n/a"
      - "prio: low"
      - "scope: convoy bridge"
    rebase-strategy: "auto"

  # Maintain dependencies for Zapier Integration - Update once every week.
  - package-ecosystem: "npm"
    directory: "/applications/zapier_integration"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "type: dependencies"
      - "status: needs review"
      - "team: n/a"
      - "prio: low"
      - "scope: zapier"
    rebase-strategy: "auto"
